#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export DOTFILES=$HOME/.config/dotfiles

fpath=(${DOTFILES}/my-prezto/themes $fpath)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

## Setup zsh-autosuggestions
#source ~/.zsh-autosuggestions/autosuggestions.zsh
#
## Enable autosuggestions automatically
#zle-line-init() {
#    zle autosuggest-start
#}
#zle -N zle-line-init
#
## use ctrl+t to toggle autosuggestions(hopefully this wont be needed as
## zsh-autosuggestions is designed to be unobtrusive)
#bindkey '^T' autosuggest-toggle

#source .zz/z.sh

# TODO
# - chruby, chgems
# - fasd
# - symbole dokumentieren
# - git status geschleunigen
# - git symbole

# infocmp to put out info about terminal
if [[ -z "$TMUX" ]]; then
  TERM=xterm-256color
fi

export EDITOR=/usr/bin/vim

# from https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/spectrum.zsh
ZSH_SPECTRUM_TEXT=${ZSH_SPECTRUM_TEXT:-Arma virumque cano Troiae qui primus ab oris}

# Show all 256 colors with color number
function spectrum_ls() {
  for code in {000..255}; do
print -P -- "$code: %F{$code}$ZSH_SPECTRUM_TEXT%f"
  done
}

# Show all 256 colors where the background is set to specific color
function spectrum_bls() {
  for code in {000..255}; do
print -P -- "$BG[$code]$code: $ZSH_SPECTRUM_TEXT %{$reset_color%}"
  done
}

alias packages-in-experimental="aptitude search '~S~i~Aexperimental'"

